<?php
/**
 * Created by PhpStorm.
 * User: Adminstrator
 * Date: 2017/6/26
 * Time: 17:55
 */

namespace app\common\model;


use think\Db;
use think\Model;

class BaseModel extends Model
{
    protected $name = 'user';
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * 获取一张表数据列表
     * @param $table_name string 表名称
     * @param $where array 条件
     * @param $order array 排序
     * @param $p string 分页数
     * @param $size string 每页条数
     * @param $group string 分组字段
     * @return array
     */
    public function get_list($table_name, $where = [], $order = [], $p, $size, $group = '')
    {
        if ($size === false) {
            $limit = false;
        } else {
            $start = ($p - 1) * $size;
            $limit = "$start, $size";
            $count = $this->where($where)->count();
            $page = ($count / $size);
        }
        $list = Db::name($table_name)->where($where)->order($order)->limit($limit)->group($group)->select();
        $data = [];
        foreach ($list as $index => $item) {
            $data[] = $item;
        }
        $lists['list'] = $data;
        $lists['page'] = $page ?: 1;
        return $lists;
    }


    /**
     * 添加数据
     * @param $table_name array
     * @param $data array
     * @return boolean
     */

    public function add_post($table_name,$data)
    {
        if (empty($data)) {
            return false;
        }
        $insert = Db::name($table_name)->insert($data);
        if ($insert == false) {
            return false;
        }
        return true;
    }

    /**
     * 编辑数据
     * @param $table_name array
     * @param $data array
     * @param $tel string
     * @return bool
     */
    public function edit_post($table_name,$data,$tel='')
    {
        if ($tel){ //只限于修改用户修改根据手机最为条件
            $map['user_mobile'] = $tel;
        }else{
            $map['id'] = $data['id'];
            unset($data['id']);
        }
        $save = Db::name($table_name)->save($data,$map);
        if ($save === false) {
            return false;
        }
        return true;
    }

}