<?php
/**
 * Created by PhpStorm.
 * User: Adminstrator
 * Date: 2017/4/15
 * Time: 22:46
 */

namespace app\admin\model;


use think\Model;

class RoleModel extends Model
{
    protected $name = 'role';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function get_role_list($pid = 0)
    {
        $role_obj = $this->where(['pid' => $pid])->order('sort')->select();
        if (empty($role_obj)) {
            return false;
        }
        $data = [];
        foreach ($role_obj as $index => $item) {
            $tmp = [
                'id' => $item['id'],
                'name' => $item['name'],
                'pid' => $item['pid'],
                'state' => $item['state'],
                'remark' => $item['remark'],
                'add_time' => $item['add_time'],
                'update_time' => $item['update_time'],
                'sort' => $item['sort'],
            ];
//            $tmp['sub'] = $this->get_role_list($item['id']);
//            if (empty($tmp['sub'])) {
//                unset($tmp['sub']);
//            }
            $data[] = $tmp;
        }
        return $data;
    }

    public function add_role($data)
    {
        if (empty($data)) {
            return false;
        }
        $insert = $this->insert($data);
        if (!$insert) {
            return false;
        }
        return true;
    }

    public function edit_role($id, $data)
    {
        if ((empty($id) || !preg_match('/^+?[1-9][0-9]*$/', $id)) || empty($data)) {
            return false;
        }
        $save = $this->where(['id' => $id])->save($data);
        if (!$save) {
            return false;
        }
        return true;
    }
}