<?php
/**
 * Created by PhpStorm.
 * User: Adminstrator
 * Date: 2017/4/15
 * Time: 23:28
 */

namespace app\admin\model;


use think\Model;


class UserModel extends Model
{
    protected $name = 'user';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}