<?php
/**
 * Created by PhpStorm.
 * User: Adminstrator
 * Date: 2017/5/15
 * Time: 21:59
 */

namespace app\admin\controller;


use app\common\controller\AdminBase;
use app\common\Tools\AjaxCode;

class Admin extends AdminBase
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 管理用户
     */
    public function index()
    {

    }

    /**
     * 管理用户列表
     */
    public function lists()
    {

    }

    /**
     * 添加管理
     */
    public function add()
    {

    }

    /**
     * 编辑管理
     */
    public function edit()
    {

    }

    /**
     * 登录界面
     */
    public function login()
    {
        return $this->fetch('/login');
    }

    /**
     * 登录
     */
    public function login_post()
    {
        $post = $this->request->post();
        if (!captcha_check($post['verify']) || empty($post['verify'])) {
            return json(['status' => AjaxCode::PARAM_VALID, 'msg' => '验证码不正确!']);
        }

    }

    /**
     * 检查验证码
     */
    public function check_verify()
    {
        $verify = $this->request->post('verify');
        if (!captcha_check($verify) || $verify == '') {
            return json(['status' => AjaxCode::PARAM_VALID, 'msg' => '验证码不正确!']);
        } else {
            return json(['status' => AjaxCode::SUCCESS, 'msg' => '验证码不正确!']);
        }
    }
}