<?php
/**
 * Created by PhpStorm.
 * User: Adminstrator
 * Date: 2017/5/15
 * Time: 21:59
 */

namespace app\admin\controller;


use app\admin\model\AdminModel;
use app\common\controller\AdminBase;
use app\common\Tools\AjaxCode;
use think\Session;

class Admin extends AdminBase
{
    protected $admin_model;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->admin_model = new AdminModel();
    }

    /**
     * 管理用户
     */
    public function index()
    {
       return $this->fetch();
    }

    /**
     * 管理用户列表
     */
    public function lists()
    {
        $p = $this->request->param('p');
        if ($p < 1 || !is_numeric($p)) {
            $p = 1;
        }
        $size = 3;
        $list = $this->admin_model->get_admin_list($p, $size);
        $data = [
            'status' => 200,
            'msg' => '获取成功',
            'data' => ['list' => $list['list']],
            'pages' => $list['page'],
        ];
        return json($data);
    }

    /**
     * 用户信息
     */
    public function admin_info()
    {
        $id = request()->param('id');
        if (empty($id) || !check_id($id)){
            return json(['status' => AjaxCode::PARAM_EMPTY, 'msg' => '参数错误!']);
        }
        $admin_info = $this->admin_model->by_id_admin($id);
        $this->assign('info', $admin_info);
        return $this->fetch();
    }

    /**
     * 添加管理
     */
    public function add()
    {
        $post = request()->port();

    }

    /**
     * 编辑管理
     */
    public function edit()
    {

    }

    /**
     * 登录界面
     */
    public function login()
    {
        return $this->fetch('/login');
    }

    /**
     * 登录
     */
    public function login_post()
    {
        $post = $this->request->post();
        if (!captcha_check($post['verify']) || empty($post['verify'])) {
            return json(['status' => AjaxCode::PARAM_VALID, 'msg' => '验证码不正确!']);
        }

    }

    /**
     * 检查验证码
     */
    public function check_verify()
    {
        $verify = $this->request->post('verify');
        if (!captcha_check($verify) || $verify == '') {
            return json(['status' => AjaxCode::PARAM_VALID, 'msg' => '验证码不正确!']);
        } else {
            return json(['status' => AjaxCode::SUCCESS, 'msg' => '验证码不正确!']);
        }
    }

    public function exit_login()
    {
        Session::delete('sys_admin');
        $this->redirect(url('admin/login'));
    }
}