<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/26
 * Time: 13:24
 */

namespace app\admin\controller;


use app\admin\model\MenuModel;
use app\common\controller\AdminBase;

class Index extends AdminBase
{
    protected $menu_model;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->menu_model = new MenuModel();
    }

    /**
     * 后台首页
     */
    public function index()
    {
        return $this->fetch('/index');
    }

    /**
     * 获取菜单
     */
    public function get_menu()
    {
        $msg['data']['list'] = $this->menu_model->get_menu($this->uid,0);
        $msg['status'] = 200;
        return json($msg);
    }

    /**
     * 获取首页信息
     */
    public function welcome()
    {
        return $this->fetch('/welcome');
    }

}