<?php
/**
 * Created by PhpStorm.
 * User: Adminstrator
 * Date: 2017/4/15
 * Time: 22:37
 */

namespace app\admin\controller;


use app\admin\model\MenuModel;
use app\admin\model\RoleModel;
use app\common\controller\AdminBase;

class Role extends AdminBase
{
    protected $role_model,$menu_model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->role_model = new RoleModel();
        $this->menu_model = new MenuModel();
    }

    public function index()
    {
        return $this->fetch();
    }

    public function lists()
    {
        $p = $this->request->param('p');

        if ($p < 1 || !is_numeric($p)) {
            $p = 1;
        }
        $size = 3;
        $list = $this->role_model->get_role_list(0, $p, $size);
        $data = [
            'status' => 200,
            'msg'    => '获取成功',
            'data'   => ['list' => $list['list']],
            'pages'  => $list['page'],
        ];

        return json($data);
    }

    /**
     * 增加角色
     */
    public function add()
    {
        return $this->fetch();
    }

    /**
     * 编辑角色
     */
    public function edit()
    {
        return $this->fetch();
    }

    /**
     * 编辑权限
     */
    public function edit_role()
    {

        $list = $this->menu_model->get_tree(0);
        $data = $this->create_role($list,0);
        $role = '<ul>'.$data.'</ul>';
        $this->assign('data',$role);
        return $this->fetch();
    }

    public function create_role($data=[], $level){
        $tmp = '';
        $a = '';
        $b = '';
        if($level == 0){
            $a = '<li>';
            $b = '</li>';
        } elseif ($level == 1){
            $a = '<dl>';
            $b = '</dl>';
        }elseif ($level == 2){
            $a = '<dd>';
            $b = '</dd>';
        }elseif ($level == 3){
            $a = '<dt>';
            $b = '</dt>';
        }
        foreach ($data as $index => $item){
            $tmp .= $a."<input type='checkbox' name='status1' value='1' title='{$item['name']}' lay-filter='role'/>";
            if(!empty($item['sub'])){
                $tmp .= $this->create_role($item['sub'],$level+1);
            }
            $tmp .= $b;
        }
        return $tmp;
    }
    /**
     * 增加角色处理数据
     */
    public function add_post()
    {

    }

    /**
     * 编辑权限数据处理
     */
    public function edit_role_post()
    {

    }

    /**
     * 编辑角色处理数据
     */
    public function edit_post()
    {

    }

    /**
     * 排序
     */
    public function set_sort()
    {

    }

    /**
     * 状态
     */
    public function set_status()
    {

    }

    public function d()
    {

    }
}
