<?php
/**
 * Created by PhpStorm.
 * User: Adminstrator
 * Date: 2017/4/15
 * Time: 18:14
 */

namespace app\admin\controller;


use app\common\controller\AdminBase;
use app\common\Tools\AjaxCode;

class User extends AdminBase
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

}